### ISSUE TITLE
[BUG] Link of playlists get parsed incorrectly

### ISSUE THREAD

**Issue by TMaddox** [plainerman/TicTacTube#23]
Expected Behavior:
When I paste this link: https://www.youtube.com/watch?v=vZv9-TWdBJM&list=PL7zsB-C3aNu03RwSy2Bn3Ov3oaEReOlT5&index=2 the file Dr. Dre - The Next Episode (San Holo Remix) should be downloaded

Actual behaviour:
The file Melanie Martinez - Soap (Excellence Remix) is downloaded

Possible explanation:
The link isn't parsed correctly, due to it linking to a playlist, not a single item.

**Comment by plainerman** [comment]
Youtube-DL was implemented to add a versatile downloader for resources with built-in file conversion. As the license agreement of YouTube forbids downloading, I cannot officially support downloading from YouTube and hence neither test / reproduce this issue. 

If you can reproduce this issue on a site that allows downloading, please come back to me. In the meantime, I will close this issue.

If you would like to fix it yourself, feel free to submit a PR. Code that violates any copyright (e.g. a unit test downloading this video) will not be merged.
